const RELEASE_HISTORY = [
  {
    id: "2026-08-13-file-return",
    version: "0.1.1",
    sequence: 1,
    title: "File return",
    notes: [
      "Added sending generated files from Codex back to Telegram.",
      "Added multiple outgoing documents per final answer.",
      "Blocked sensitive paths such as .env, logs, data, .git and service folders.",
    ],
  },
  {
    id: "2026-08-14-release-notes",
    version: "0.1.2",
    sequence: 2,
    title: "Release notes",
    notes: [
      "Added startup version journal in data/releases.jsonl.",
      "Added restart, update and rollback detection without reading git at runtime.",
      "Added Telegram commands /release and /releases.",
    ],
  },
  {
    id: "2026-08-19-model-settings",
    version: "0.1.3",
    sequence: 3,
    title: "Model settings",
    notes: [
      "Added /model to show the current Codex model and reasoning effort.",
      "Added changing the model and reasoning effort for the selected chat.",
      "Model and effort choices are read dynamically from Codex app-server.",
    ],
  },
  {
    id: "2026-08-19-document-batch-hardening",
    version: "0.1.4",
    sequence: 4,
    title: "Document batch hardening",
    notes: [
      "Loose Telegram documents without media_group_id are now collected longer before starting a Codex turn.",
      "Document prompts now require processing every listed file before focusing on one document.",
      "Uploaded originals are treated as read-only, and Codex is told to avoid PowerShell Get-Content/Set-Content for encoding fixes.",
    ],
  },
  {
    id: "2026-08-19-document-processing-queue",
    version: "0.1.5",
    sequence: 5,
    title: "Document processing queue",
    notes: [
      "Telegram document handling is split into accept, store and process steps.",
      "Saved document batches are put into a per-thread processing queue before Codex starts work.",
      "Queued document batches wait for the active Codex turn instead of being rejected as a busy chat.",
    ],
  },
  {
    id: "2026-08-19-incoming-message-batching",
    version: "0.1.6",
    sequence: 6,
    title: "Incoming message batching",
    notes: [
      "Non-command Telegram text and documents are now collected into one incoming message batch.",
      "The bot waits for a quiet period before processing, so one user request split across messages stays together.",
      "Processing starts only after the full batch is accepted and stored.",
    ],
  },
  {
    id: "2026-08-19-unified-intake-quiet-period",
    version: "0.1.7",
    sequence: 7,
    title: "Unified intake quiet period",
    notes: [
      "All non-command Telegram text and document updates now use the same quiet period.",
      "A document followed by a text instruction is kept in one incoming batch before processing.",
      "Queued Telegram work starts after an external Desktop turn becomes idle.",
      "Removed the obsolete direct single-document handling path.",
    ],
  },
  {
    id: "2026-08-20-outgoing-file-path-detection",
    version: "0.1.8",
    sequence: 8,
    title: "Outgoing file path detection",
    notes: [
      "Outgoing file detection now recognizes Codex markdown links with C:/ Windows paths.",
      "Wrapped Windows paths such as C: followed by \\Users on the next line are rejoined before matching.",
      "File names with underscores are preserved when extracting paths for Telegram document sending.",
    ],
  },
  {
    id: "2026-08-23-writer-lease",
    version: "0.1.9",
    sequence: 9,
    title: "Shared thread writer lease",
    notes: [
      "Telegram bot now keeps selected Codex chats observable without holding a writer lock forever.",
      "Writer access is leased only for actions that write to Codex, then released after an idle timeout.",
      "If Codex Desktop already owns the selected chat writer, Telegram reports the busy state instead of failing the request.",
    ],
  },
  {
    id: "2026-08-25-full-remote-access",
    version: "0.1.10",
    sequence: 10,
    title: "Full remote access and thread release",
    notes: [
      "Full access is applied to the app-server, old and new threads, and every Telegram-started turn.",
      "Telegram unsubscribes from a thread after work so Codex Desktop can open it immediately.",
      "Added /access, /unlock and remote answers for Codex and MCP questions.",
      "Added an optional automatic fork when Codex Desktop keeps the original thread writer.",
      "Read-only history polling now works after the Telegram app-server unsubscribes.",
    ],
  },
  {
    id: "2026-08-25-telegram-topics",
    version: "0.1.11",
    sequence: 11,
    title: "Telegram topics for Codex chats",
    notes: [
      "Added /sync_topics to create Telegram topics for recent Codex chats.",
      "Incoming Telegram topic messages are routed to the mapped Codex chat without using /use.",
      "Codex replies and generated documents are sent back to the same Telegram topic.",
    ],
  },
  {
    id: "2026-08-25-topic-auth-hardening",
    version: "0.1.12",
    sequence: 12,
    title: "Telegram topic authorization hardening",
    notes: [
      "Bot and Telegram service messages from topic creation are ignored before authorization checks.",
      "Anonymous admin messages do not run commands and do not fill topics with access-denied replies.",
      "Unauthorized /sync_topics commands are covered by tests so they cannot create topics.",
    ],
  },
  {
    id: "2026-08-27-new-thread-recovery",
    version: "0.1.13",
    sequence: 13,
    title: "Reliable new chats",
    notes: [
      "New Codex chats stay attached until their first Telegram task creates a persisted rollout.",
      "A new chat left unmaterialized by a bot restart is recreated automatically before processing.",
      "Legacy orphaned chats that report no rollout are recovered without manual chat selection.",
    ],
  },
  {
    id: "2026-08-27-accurate-queue-notices",
    version: "0.1.14",
    sequence: 14,
    title: "Accurate queue notices",
    notes: [
      "Normal Telegram messages start without a misleading queue notification.",
      "Document batches also stay silent unless they are actually waiting for a busy Codex chat.",
      "Queue notices are now reserved for real Desktop or Telegram writer contention.",
    ],
  },
  {
    id: "2026-08-27-cross-chat-access",
    version: "0.1.15",
    sequence: 15,
    title: "Cross-chat access for Telegram",
    notes: [
      "Telegram-started Codex tasks can now find and read other local Codex chats, including archived history.",
      "The read-only chat bridge is attached to old, new, and automatically forked chats.",
      "Added CODEX_APP_TOOLS_ENABLED so cross-chat access can be disabled independently of filesystem, network, and SSH access.",
      "/access and /status now report whether cross-chat tools are enabled.",
    ],
  },
  {
    id: "2026-08-27-cross-chat-send-and-runtime-recovery",
    version: "0.1.16",
    sequence: 16,
    title: "Complete cross-chat actions",
    notes: [
      "Telegram tasks now receive their exact current Codex thread ID in application context.",
      "Added a tool that queues an explicitly requested message in another Codex chat, including when that chat is busy.",
      "Codex binary discovery now prefers a complete Desktop runtime containing codex-code-mode-host.exe.",
      "This restores shell, SSH, skills, and other code-mode tools after an incomplete Codex cleanup leaves duplicate binaries.",
    ],
  },
  {
    id: "2026-09-07-new-thread-visibility",
    version: "0.1.17",
    sequence: 17,
    title: "New thread visibility",
    notes: [
      "A newly created Telegram-selected Codex chat is kept at the top of /chats even before thread/list returns it.",
      "Empty new chats with unavailable turn history are treated as an empty sync baseline.",
      "Desktop answer polling no longer repeats warnings for freshly created chats without history.",
    ],
  },
  {
    id: "2026-09-07-current-thread-topic-sync",
    version: "0.1.18",
    sequence: 18,
    title: "Reliable topic synchronization",
    notes: [
      "Topic synchronization includes the selected chat even before Codex lists its history.",
      "The requested topic sync limit is preserved when adding the selected chat.",
      "Rebinding a Telegram topic removes the old reverse mapping; sync also repairs stale mappings from earlier versions.",
    ],
  },
  {
    id: "2026-09-07-expanded-regression-tests",
    version: "0.1.19",
    sequence: 19,
    title: "Expanded regression coverage",
    notes: [
      "Added 62 tests for topics, persisted recovery, authorization, Telegram API errors and binary file delivery.",
      "Topic chat-list buttons now highlight the chat selected in that topic.",
      "Fractional topic sync limits are normalized to integers before calling Codex.",
      "Added npm run test:coverage for repeatable coverage reports.",
    ],
  },
  {
    id: "2026-09-08-new-chat-model-settings",
    version: "0.1.20",
    sequence: 20,
    title: "Model settings before the first message",
    notes: [
      "Viewing /model reads thread metadata or effective configuration without resuming the chat or releasing its writer.",
      "Model choices for empty chats survive restarts and are applied before the first message, with retry on failure.",
      "/model list no longer requires a selected or loaded chat.",
      "Added lifecycle regression tests across bot commands, CodexClient and persisted state.",
    ],
  },
  {
    id: "2026-09-12-configurable-outgoing-file-access",
    version: "0.1.21",
    sequence: 21,
    title: "Configurable full outgoing file access",
    notes: [
      "Added TELEGRAM_OUTGOING_FILE_ACCESS with off, workspace, and all modes.",
      "Full mode can send referenced files from any readable local path, including files created in other Codex chats.",
      "Added configurable outgoing file size and per-answer count limits; zero disables each bot-side limit.",
      "/access and /status now expose the effective outgoing file access mode.",
    ],
  },
  {
    id: "2026-09-12-confirm-chat-fork",
    version: "0.1.22",
    sequence: 22,
    title: "Confirm forks for blocked chats",
    notes: [
      "Added CODEX_ACTIVE_WRITER_MODE=ask for explicit Telegram confirmation when a chat is blocked by Desktop.",
      "The owner can create a copy and run the saved message or cancel it without continuing the Codex dialogue.",
      "Pending decisions survive bot restarts and duplicate messages do not bypass the confirmation.",
    ],
  },
];

const CURRENT_RELEASE = RELEASE_HISTORY.at(-1);

module.exports = { CURRENT_RELEASE, RELEASE_HISTORY };
